name: crudo_app
description: CRUDO Milk Delivery App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/cow_milk.png
    - assets/images/buffalo_milk.png
