name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - name: Flutter doctor
        run: flutter doctor

      # ✅ Ensure valid project name (VERY IMPORTANT)
      - name: Ensure valid project
        run: |
          echo "Project name check..."
          if grep -q "name: crudo_app" pubspec.yaml; then
            echo "Project name OK"
          else
            echo "Invalid project name. Fix pubspec.yaml"
            exit 1
          fi

      # ✅ Create Android folder if missing
      - name: Create Android folders
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
